-- DesaynScale Elite launch automation.
-- The first 10 successful Elite buyers receive the download automatically by email.

CREATE TABLE IF NOT EXISTS public.elite_desaynscale_promo_claims (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  email text NOT NULL,
  payment_source text NOT NULL CHECK (payment_source IN ('gcash', 'paymongo', 'dodo')),
  payment_id text NOT NULL,
  claim_number integer NOT NULL CHECK (claim_number BETWEEN 1 AND 10),
  access_type text NOT NULL DEFAULT 'lifetime',
  delivery_status text NOT NULL DEFAULT 'pending'
    CHECK (delivery_status IN ('pending', 'sent', 'failed')),
  delivered_at timestamp with time zone,
  delivery_error text,
  claimed_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE (payment_source, payment_id),
  UNIQUE (user_id),
  UNIQUE (claim_number)
);

ALTER TABLE public.elite_desaynscale_promo_claims ENABLE ROW LEVEL SECURITY;

-- Bring across only DesaynScale-era entitlements. Imported claims are marked sent
-- because their delivery was already handled manually before this automation.
WITH eligible AS (
  SELECT DISTINCT ON (legacy.user_id)
    legacy.user_id,
    legacy.email,
    legacy.payment_source,
    legacy.payment_id,
    legacy.claimed_at
  FROM public.elite_autoresizer_promo_claims AS legacy
  WHERE legacy.claimed_at >= timestamp with time zone '2026-08-31 13:30:00+00'
    AND legacy.payment_source IN ('gcash', 'paymongo', 'dodo')
  ORDER BY legacy.user_id, legacy.claimed_at, legacy.id
), ranked AS (
  SELECT
    eligible.*,
    row_number() OVER (ORDER BY eligible.claimed_at, eligible.payment_id)::integer AS new_claim_number
  FROM eligible
)
INSERT INTO public.elite_desaynscale_promo_claims (
  user_id,
  email,
  payment_source,
  payment_id,
  claim_number,
  delivery_status,
  delivered_at,
  claimed_at
)
SELECT
  ranked.user_id,
  lower(trim(ranked.email)),
  ranked.payment_source,
  ranked.payment_id,
  ranked.new_claim_number,
  'sent',
  ranked.claimed_at,
  ranked.claimed_at
FROM ranked
WHERE ranked.new_claim_number <= 10
ON CONFLICT DO NOTHING;

CREATE OR REPLACE FUNCTION public.claim_elite_desaynscale_promo(
  claim_user_id uuid,
  claim_email text,
  claim_payment_source text,
  claim_payment_id text
)
RETURNS TABLE(
  granted boolean,
  already_entitled boolean,
  claim_number integer,
  slots_remaining integer
) AS $$
DECLARE
  existing_claim public.elite_desaynscale_promo_claims%ROWTYPE;
  used_slots integer;
  new_claim_number integer;
BEGIN
  IF claim_payment_source NOT IN ('gcash', 'paymongo', 'dodo') THEN
    RAISE EXCEPTION 'Invalid DesaynScale promo payment source';
  END IF;

  PERFORM pg_advisory_xact_lock(hashtext('syncraft-elite-desaynscale-promo'));

  SELECT * INTO existing_claim
  FROM public.elite_desaynscale_promo_claims AS promo
  WHERE promo.payment_source = claim_payment_source
    AND promo.payment_id = claim_payment_id;

  IF FOUND THEN
    SELECT count(*)::integer INTO used_slots
    FROM public.elite_desaynscale_promo_claims;
    RETURN QUERY SELECT false, true, existing_claim.claim_number, GREATEST(0, 10 - used_slots);
    RETURN;
  END IF;

  SELECT * INTO existing_claim
  FROM public.elite_desaynscale_promo_claims AS promo
  WHERE promo.user_id = claim_user_id;

  IF FOUND THEN
    SELECT count(*)::integer INTO used_slots
    FROM public.elite_desaynscale_promo_claims;
    RETURN QUERY SELECT false, true, existing_claim.claim_number, GREATEST(0, 10 - used_slots);
    RETURN;
  END IF;

  SELECT count(*)::integer INTO used_slots
  FROM public.elite_desaynscale_promo_claims;

  IF used_slots >= 10 THEN
    RETURN QUERY SELECT false, false, NULL::integer, 0;
    RETURN;
  END IF;

  new_claim_number := used_slots + 1;

  INSERT INTO public.elite_desaynscale_promo_claims (
    user_id,
    email,
    payment_source,
    payment_id,
    claim_number
  ) VALUES (
    claim_user_id,
    lower(trim(claim_email)),
    claim_payment_source,
    claim_payment_id,
    new_claim_number
  );

  RETURN QUERY SELECT true, false, new_claim_number, 10 - new_claim_number;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

REVOKE ALL ON FUNCTION public.claim_elite_desaynscale_promo(uuid, text, text, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.claim_elite_desaynscale_promo(uuid, text, text, text) FROM authenticated;
REVOKE ALL ON FUNCTION public.claim_elite_desaynscale_promo(uuid, text, text, text) FROM anon;
GRANT EXECUTE ON FUNCTION public.claim_elite_desaynscale_promo(uuid, text, text, text) TO service_role;

NOTIFY pgrst, 'reload schema';
