-- Elite launch promo: the first 10 successful Elite buyers receive a lifetime
-- Subli Autoresizer entitlement. Run once in the Supabase SQL Editor.

-- Snapshot the exact terms shown when a manual GCash request is submitted.
-- Existing rows are backfilled with the pricing that was live before this launch.
ALTER TABLE public.payment_requests
  ADD COLUMN IF NOT EXISTS amount integer,
  ADD COLUMN IF NOT EXISTS credits integer;

UPDATE public.payment_requests
SET
  amount = CASE lower(plan)
    WHEN 'tingi' THEN 5000
    WHEN 'basic' THEN 10000
    WHEN 'starter' THEN 29900
    WHEN 'pro' THEN 49900
    WHEN 'elite' THEN 79900
    ELSE amount
  END,
  credits = CASE lower(plan)
    WHEN 'tingi' THEN 24
    WHEN 'basic' THEN 48
    WHEN 'starter' THEN 156
    WHEN 'pro' THEN 300
    WHEN 'elite' THEN 540
    ELSE credits
  END
WHERE amount IS NULL OR credits IS NULL;

CREATE TABLE IF NOT EXISTS public.elite_autoresizer_promo_claims (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  email text NOT NULL,
  payment_source text NOT NULL CHECK (payment_source IN ('gcash', 'dodo')),
  payment_id text NOT NULL,
  claim_number integer NOT NULL CHECK (claim_number BETWEEN 1 AND 10),
  access_type text NOT NULL DEFAULT 'lifetime',
  claimed_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE (payment_source, payment_id),
  UNIQUE (user_id),
  UNIQUE (claim_number)
);

ALTER TABLE public.elite_autoresizer_promo_claims ENABLE ROW LEVEL SECURITY;

-- Deliberately no public policies. Claims are created and counted only through
-- server routes that use the Supabase service role.

CREATE OR REPLACE FUNCTION public.claim_elite_autoresizer_promo(
  claim_user_id uuid,
  claim_email text,
  claim_payment_source text,
  claim_payment_id text
)
RETURNS TABLE(
  granted boolean,
  already_entitled boolean,
  claim_number integer,
  slots_remaining integer
) AS $$
DECLARE
  existing_claim public.elite_autoresizer_promo_claims%ROWTYPE;
  used_slots integer;
  new_claim_number integer;
BEGIN
  IF claim_payment_source NOT IN ('gcash', 'dodo') THEN
    RAISE EXCEPTION 'Invalid Elite promo payment source';
  END IF;

  -- Serializes claims so two successful payments cannot take the same final slot.
  PERFORM pg_advisory_xact_lock(hashtext('syncraft-elite-autoresizer-promo'));

  SELECT * INTO existing_claim
  FROM public.elite_autoresizer_promo_claims AS promo
  WHERE promo.payment_source = claim_payment_source
    AND promo.payment_id = claim_payment_id;

  IF FOUND THEN
    SELECT count(*)::integer INTO used_slots
    FROM public.elite_autoresizer_promo_claims;
    RETURN QUERY SELECT false, true, existing_claim.claim_number, GREATEST(0, 10 - used_slots);
    RETURN;
  END IF;

  SELECT * INTO existing_claim
  FROM public.elite_autoresizer_promo_claims AS promo
  WHERE promo.user_id = claim_user_id;

  IF FOUND THEN
    SELECT count(*)::integer INTO used_slots
    FROM public.elite_autoresizer_promo_claims;
    RETURN QUERY SELECT false, true, existing_claim.claim_number, GREATEST(0, 10 - used_slots);
    RETURN;
  END IF;

  SELECT count(*)::integer INTO used_slots
  FROM public.elite_autoresizer_promo_claims;

  IF used_slots >= 10 THEN
    RETURN QUERY SELECT false, false, NULL::integer, 0;
    RETURN;
  END IF;

  new_claim_number := used_slots + 1;

  INSERT INTO public.elite_autoresizer_promo_claims (
    user_id, email, payment_source, payment_id, claim_number
  ) VALUES (
    claim_user_id,
    lower(trim(claim_email)),
    claim_payment_source,
    claim_payment_id,
    new_claim_number
  );

  -- Reuse the existing Store fulfillment queue so the owner can send the
  -- download/license and mark the free lifetime bonus as delivered.
  IF to_regclass('public.store_requests') IS NOT NULL THEN
    INSERT INTO public.store_requests (
      user_id,
      email,
      product_name,
      product_type,
      price,
      receipt_url,
      status
    ) VALUES (
      claim_user_id,
      lower(trim(claim_email)),
      'Subli Autoresizer — Elite Launch Bonus',
      'Lifetime entitlement #' || new_claim_number,
      'FREE',
      NULL,
      'pending'
    );
  END IF;

  RETURN QUERY SELECT true, false, new_claim_number, 10 - new_claim_number;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

REVOKE ALL ON FUNCTION public.claim_elite_autoresizer_promo(uuid, text, text, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.claim_elite_autoresizer_promo(uuid, text, text, text) FROM authenticated;
REVOKE ALL ON FUNCTION public.claim_elite_autoresizer_promo(uuid, text, text, text) FROM anon;
GRANT EXECUTE ON FUNCTION public.claim_elite_autoresizer_promo(uuid, text, text, text) TO service_role;

NOTIFY pgrst, 'reload schema';
